import ast
import pathlib
import datetime
import warnings


_NODES_INIT_TEMPLATE = """# noqa: D104
from juturna.components._node_builder._utils import _lazy_node_loaders


_AVAILABLE_PLUGINS: dict[str, str] = {}


__getattr__, __dir__ = _lazy_node_loaders(__name__, _AVAILABLE_PLUGINS)
__all__ = list(_AVAILABLE_PLUGINS.keys())
"""


def node_stub(
    node_name: str,
    package: str,
    node_class: str | None = None,
    author: str = '',
    email: str = '',
    destination_folder: str = './src',
):
    """
    Create a basic node template with a config file and a README file.

    The command is meant to be executed in the root of a node repository. The
    node is created in the ``juturna.contrib.<package>.nodes`` namespace, so in
    ``<destination_folder>/juturna/contrib/<package>/nodes/_<node_name>``, and
    registered in the ``__init__.py`` file of the nodes package (created if
    missing). Once the repository is installed, the node can be used in a
    pipeline with type ``contrib.<package>.nodes.<node_class>``.

    Parameters
    ----------
    node_name : str
        The name of the node. This is the name of the folder and the module
        that will be created. Do not prefix the name with a underscore, as this
        will be done automatically.
    package : str
        Name of the contrib package the node belongs to, usually the author or
        organisation name.
    node_class : str
        The name of the class that will be created in the node file. If not
        provided, the class name will be generated by capitalising the first
        letter of each word in the node name, splitting by underscores.
    author : str
        Name of the node author.
    email : str
        Email address of the corresponding node author.
    destination_folder : str
        The source folder of the node repository, containing the juturna
        namespace. The default is './src'.

    """
    if node_class is None:
        node_class = ''.join(x.capitalize() for x in node_name.split('_'))

    for label, value in (
        ('node name', node_name),
        ('package', package),
        ('node class', node_class),
    ):
        if not value.isidentifier():
            raise ValueError(f'{label} {value!r} is not a valid identifier')

    package_root = pathlib.Path(
        destination_folder, 'juturna', 'contrib', package
    )
    nodes_root = package_root / 'nodes'
    node_destination = nodes_root / f'_{node_name}'

    if node_destination.exists():
        warnings.warn(
            f'Node {node_name} already exists in {node_destination}. '
            'Please choose a different name or delete the existing node.',
            UserWarning,
            stacklevel=1,
        )

        return

    # juturna and juturna.contrib are namespace packages shared by all the
    # installed node repositories, so they must not get an __init__.py file
    node_destination.mkdir(parents=True)
    (package_root / '__init__.py').touch()

    base_path = pathlib.Path(__file__).parent

    template_path = base_path / 'basic_node.template'
    config_path = base_path / 'basic_config.template'

    with open(template_path) as template_file:
        template = template_file.read()

    template = template.replace('$_node_class_name', node_class)
    template = template.replace('$_node_author_name', author)
    template = template.replace('$_node_author_email', email)
    template = template.replace(
        '$_creation_datetime',
        datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    )

    node_file_path = pathlib.Path(node_destination, f'{node_name}.py')

    with open(node_file_path, 'w') as node_file:
        node_file.write(template)

    with open(config_path) as config_content:
        config = config_content.read()

    with open(pathlib.Path(node_destination, 'config.toml'), 'w') as cfg_file:
        cfg_file.write(config)

    node_type = f'contrib.{package}.nodes.{node_class}'

    with open(pathlib.Path(node_destination, 'README.md'), 'w') as readme_file:
        readme_file.write(
            f'# {node_name}\n\n'
            f'## Node type: {node_type}\n\n'
            f'## Node class name: {node_class}\n\n'
            f'## Node name: {node_name}\n\n'
        )

    open(pathlib.Path(node_destination, 'requirements.txt'), 'a').close()

    _register_node(
        nodes_root / '__init__.py', node_class, f'._{node_name}.{node_name}'
    )

    print(f'Node creation successful! Node type: {node_type}')


def _register_node(init_path: pathlib.Path, node_class: str, module: str):
    """
    Add a node to the _AVAILABLE_PLUGINS mapping of a nodes package

    The mapping is rewritten with the existing entries followed by the new
    one, so comments placed inside the mapping are not preserved.
    """
    if not init_path.exists():
        init_path.write_text(_NODES_INIT_TEMPLATE)

    source = init_path.read_bytes()
    mapping = _find_plugins_mapping(ast.parse(source))

    # dict unpacking (**other) has no key, and cannot be rewritten
    keys = [k for k in mapping.keys if k is not None] if mapping else []

    if (
        mapping is None
        or len(keys) != len(mapping.values)
        or mapping.end_lineno is None
        or mapping.end_col_offset is None
    ):
        warnings.warn(
            f'_AVAILABLE_PLUGINS mapping not found in {init_path}, please add '
            f"'{node_class}': '{module}' to it manually",
            UserWarning,
            stacklevel=2,
        )

        return

    entries = {
        ast.literal_eval(k): ast.literal_eval(v)
        for k, v in zip(keys, mapping.values, strict=True)
    }

    if node_class in entries:
        warnings.warn(
            f'{node_class} is already registered in {init_path} as '
            f'{entries[node_class]}, the mapping was not updated',
            UserWarning,
            stacklevel=2,
        )

        return

    entries[node_class] = module
    new_mapping = '{\n'
    new_mapping += ''.join(f'    {k!r}: {v!r},\n' for k, v in entries.items())
    new_mapping += '}'

    # ast offsets are utf-8 byte offsets, so the mapping is replaced in the
    # encoded source
    lines = source.splitlines(keepends=True)
    start = sum(map(len, lines[: mapping.lineno - 1])) + mapping.col_offset
    end = sum(map(len, lines[: mapping.end_lineno - 1]))
    end += mapping.end_col_offset

    init_path.write_bytes(source[:start] + new_mapping.encode() + source[end:])


def _find_plugins_mapping(tree: ast.Module) -> ast.Dict | None:
    for statement in tree.body:
        if isinstance(statement, ast.AnnAssign):
            targets = [statement.target]
        elif isinstance(statement, ast.Assign):
            targets = statement.targets
        else:
            continue

        is_mapping = any(
            isinstance(t, ast.Name) and t.id == '_AVAILABLE_PLUGINS'
            for t in targets
        )

        if is_mapping and isinstance(statement.value, ast.Dict):
            return statement.value

    return None
